[package]
name = "auth-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.89"
axum = "0.8.8"
axum-extra = { version = "0.12.5", features = ["cookie"] }
chrono = "0.4.44"
dotenvy = "0.15.7"
jsonwebtoken = { version = "10.3.0", default-features = false, features = ["rust_crypto"] }
lazy_static = "1.5.0"
regex = "1.12.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.50.0", features = ["full"] }
tower-http = { version = "0.6.8", features = ["fs", "cors", "trace"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["registry", "env-filter"] }
tracing-error = "0.2.1"
thiserror = "2.0.17"
color-eyre = "0.6.5"
uuid = { version = "1.22.0", features = ["v4", "serde"] }
rand = "0.10.0"
argon2 = { version = "=0.5.3", features = ["std"] }
redis = { version = "0.32.7", features = ["tokio-comp"] }
sqlx = { version = "=0.8.6", features = [ "runtime-tokio-rustls", "postgres", "migrate"] }
validator = "=0.20.0"
secrecy = { version = "0.10.3", features = ["serde"] }
reqwest = { version = "0.13.2", default-features = false, features = ["json", "rustls", "cookies"] }

[dev-dependencies]
fake = "=4.4.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.2.0"
rand = "0.10.0"
serde_json = "1.0.149"
wiremock = "0.6.5"
